"""
Streamlit page for converting PDF reports to ngTeco CSV format.
Extracts IN/OUT times and dates from PDF reports and converts them to ngTeco CSV.
"""

import streamlit as st
from datetime import datetime
from io import BytesIO
import pandas as pd

from streamlit_extras.switch_page_button import switch_page
from pdf_to_ngteco_script import convert_pdf_to_ngteco_csv


def main():
    if "logged_in" not in st.session_state or not st.session_state["logged_in"]:
        st.error("You need to log in first.")
        st.session_state["logged_in"] = False
        st.session_state["user_id"] = None
        switch_page("Login")
        return

    st.title("📄 PDF to ngTeco CSV Converter")
    
    st.markdown("""
    <div style="background-color: #e8f5e9; padding: 15px; border-radius: 5px; border-left: 4px solid #4caf50; margin-bottom: 20px;">
        <strong>ℹ️ About This Tool</strong><br>
        Upload PDF reports generated by the platform and extract IN/OUT times and dates to convert them into ngTeco CSV format.
        This tool automatically extracts table data from PDFs and generates the proper ngTeco CSV format for import.
    </div>
    """, unsafe_allow_html=True)
    
    # File upload section
    st.markdown("### 📁 Upload PDF File")
    uploaded_file = st.file_uploader(
        "Choose a PDF file",
        type=['pdf'],
        help="Upload a PDF report generated by the platform (Frappe HR PDF reports)"
    )
    
    if uploaded_file is not None:
        try:
            # Read PDF content
            pdf_content = uploaded_file.read()
            
            st.success(f"✅ PDF file uploaded: {uploaded_file.name}")
            
            # Convert PDF to ngTeco CSV
            st.markdown("### 🔄 Converting PDF to ngTeco CSV")
            
            with st.spinner("Extracting data from PDF and converting to ngTeco CSV format..."):
                csv_content, error_message = convert_pdf_to_ngteco_csv(pdf_content)
            
            if error_message:
                st.error(f"❌ Conversion failed: {error_message}")
                st.info("💡 Make sure the PDF contains a table with Date, IN, and OUT columns.")
            elif csv_content:
                st.success("✅ Conversion successful!")
                
                # Display preview
                st.markdown("### 📋 Preview of ngTeco CSV")
                st.text_area(
                    "CSV Content Preview",
                    csv_content,
                    height=300,
                    disabled=True,
                    help="Preview of the generated ngTeco CSV format"
                )
                
                # Download section
                st.markdown("### 💾 Download ngTeco CSV File")
                timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
                csv_filename = f"ngteco_csv_{timestamp}.csv"
                
                st.download_button(
                    label="📥 Download ngTeco CSV File",
                    data=csv_content.encode('utf-8'),
                    file_name=csv_filename,
                    mime="text/csv",
                    use_container_width=True,
                )
                
                # Show statistics
                st.markdown("### 📊 Conversion Statistics")
                
                # Count records
                lines = csv_content.split('\n')
                data_lines = [line for line in lines if line.strip() and not line.startswith(',,,') and 'Date' not in line.lower() and 'Total Hours' not in line.lower() and 'Timecard Report' not in line]
                record_count = len(data_lines)
                
                col1, col2, col3 = st.columns(3)
                with col1:
                    st.metric("Total Records", record_count)
                with col2:
                    # Count records with IN times
                    in_count = sum(1 for line in data_lines if len(line.split(',')) > 2 and line.split(',')[2].strip())
                    st.metric("Records with IN", in_count)
                with col3:
                    # Count records with OUT times
                    out_count = sum(1 for line in data_lines if len(line.split(',')) > 3 and line.split(',')[3].strip())
                    st.metric("Records with OUT", out_count)
                
                st.info("💡 You can now use this CSV file with the 'Frappe HR Import' tool to import the data back into Frappe HR.")
        
        except Exception as e:
            st.error(f"❌ Error processing PDF file: {str(e)}")
            st.exception(e)
    
    else:
        st.info("👆 Please upload a PDF file to get started.")
        
        # Show example format
        with st.expander("📖 Expected PDF Format"):
            st.markdown("""
            The PDF should contain a table with the following columns:
            - **Date**: Work date (various formats supported)
            - **IN**: Check-in time (HH:MM format)
            - **OUT**: Check-out time (HH:MM format)
            - **Day**: Day of the week (optional, will be auto-generated if missing)
            
            The PDF should also contain:
            - **Employee name**: Extracted from the summary page
            - **Pay Period**: Date range (e.g., "2025-01-01 - 2025-01-15")
            
            **Note**: This tool works best with PDF reports generated by the "Frappe HR PDF" page.
            """)


if __name__ == "__main__":
    main()

